version: '3.3'
services:
  web:
    image: jasonsoft/abb-web:latest
    ports:
      - target: 10214
        published: 10214
        protocol: tcp
        mode: host
    networks:
      - abb
    restart: always
    logging:
      options:
        max-size: 50m
    environment:
      - ABB_WEB_API_HOST=
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause